### ISSUE TITLE
Fragments overlap when the app goes to Pause and then Resume

### ISSUE THREAD

**Issue by venkat20390** [twinone/AppLocker#11]
Fragments get overlapped sometimes when the app paused and resumed again. I have attached a screenshot of the issue.

![img-20150325-wa0001](https://cloud.githubusercontent.com/assets/3164125/6827084/806247e6-d32b-11e4-91ab-1efe9225aa01.jpg)

**Comment by twinone** [comment]
That activity should be excluded from recents, meaning that when you navigate away the activity should destroy itself.
How are you triggering the pause-resume?

**Comment by venkat20390** [comment]
oh! I didn't notice that excludeRecents in the manifest. But it was occurred to me first time when got a call. Also once when i used the home button and went to the app again. If it is not onPause and onResume, what could be the reason for this overlapping screen?

**Comment by twinone** [comment]
I'll test the calling. Home button should also just destroy the activity. On what android version are you? When I used 4.x sometimes the excludeFromRecents was buggy.

**Comment by venkat20390** [comment]
I am using Lollipop version. My device is Moto G 1st Gen.

**Comment by twinone** [comment]
Fixed in 027860dd68a3473e1ad2bbf4ddd3d207f04dadf0
