### ISSUE TITLE
Issue with Foreground colour in HTC devices

### ISSUE THREAD

**Issue by venkat20390** [twinone/AppLocker#13]
There is bug while using support library in HTC devices which causes the app background and foreground to White. It makes the app texts unreadable. The following thread contains the reason and fix for the issue -> https://code.google.com/p/android/issues/detail?id=78819 . Hope you will fix it using the suggestion in the thread.

**Comment by twinone** [comment]
Should be fixed since some time now. Please build it and tell me. If it's not fixed, just comment here.
