### ISSUE TITLE
crash: if initially Lock Type choosing is skipped

### ISSUE THREAD

**Issue by ildar** [twinone/AppLocker#14]
On the first run the app proposes to Choose the Lock Type. It may be skipped with Back button. Then the app crashes.
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): FATAL EXCEPTION: main
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): Process: com.twinone.locker, PID: 11903
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): java.lang.NullPointerException
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at org.twinone.locker.ui.a.b(Unknown Source)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at org.twinone.locker.ui.a.a(Unknown Source)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at org.twinone.locker.a.c.a(Unknown Source)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at org.twinone.locker.a.c.onPostExecute(Unknown Source)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at android.os.Looper.loop(Looper.java:136)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at android.app.ActivityThread.main(ActivityThread.java:5088)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at java.lang.reflect.Method.invokeNative(Native Method)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at java.lang.reflect.Method.invoke(Method.java:515)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
> Thu, 02 Apr 2015 12:23:47 +0600: E/AndroidRuntime(11903): 	at dalvik.system.NativeStart.main(Native Method)
> Thu, 02 Apr 2015 12:23:47 +0600: W/ActivityManager(  462):   Force finishing activity com.twinone.locker/.MainActivityAlias

**Comment by twinone** [comment]
I can't get the bug to show up on my device. I'm using the latest version of AppLocker and Android Lollipop. What are you using?

**Comment by ashu9415** [comment]
i am also uding lollipop

**Comment by ildar** [comment]
4.4.2
did you stop the app and wipe data?
>
>

**Comment by twinone** [comment]
Also please use the latest version. I can't seem to reproduce it. I've tried on various lollipop devices.

**Comment by ildar** [comment]
4.4.2 isn't Lollipop, it is KitKat
>
>

**Comment by ashu9415** [comment]
i know ...sir

**Comment by twinone** [comment]
Probably fixed by now. Could you check it's working now?
