### ISSUE TITLE
Not working with android 5.1.

### ISSUE THREAD

**Issue by nishant-git** [twinone/AppLocker#15]

**Comment by ashu9415** [comment]
yes...

**Comment by twinone** [comment]
Possible issue: Top package name not available anymore (see [here](https://github.com/twinone/AppLocker/blob/3c93c4c5b4b70a64f421e6008f3d3dcaa17a3351/app/src/main/java/org/twinone/locker/lock/AppLockService.java#L361-L373) and [here](
http://stackoverflow.com/questions/24625936/getrunningtasks-doesnt-work-in-android-l/27140347#27140347))

Google decided to remove the getRunningTasks() access in Lollipop, but in 5.0 they forgot the getRunningAppProcesses() returned the top package name. This may now be fixed. I'll test it when I have some time.

**Comment by nishant-git** [comment]
usage stats along with usage permission will help?

**Comment by wangjinyu501** [comment]
I have used some other app lock,they are working on  5.1.

**Comment by nishant-git** [comment]
http://stackoverflow.com/questions/24625936/getrunningtasks-doesnt-work-in-android-l

check this out.

**Comment by varoon** [comment]
Hi just wanted to check if this issue is solved ?

**Comment by twinone** [comment]
Issue: App Locker says it's enabled but fails to show the lock screen when a locked app is opened (sometimes)

Possible causes: [this](http://stackoverflow.com/questions/29914724/scheduling-alarm-for-every-second-in-android-5-1) and [this](https://commonsware.com/blog/2015/03/23/alarmmanager-regression-android-5p1.html)
> Suspiciously short interval XXX millis; expanding to 60 seconds

Possible solutions: Without looking at the code yet, I'd say a workaround is to use recursion: Setting a new alarm inside of the previous one, instead of using a repeating alarm.

Will fix in branch: fix-android5.1

**Comment by twinone** [comment]
Looking at [the source code for AlarmManagerService](https://github.com/android/platform_frameworks_base/blob/master/services/core/java/com/android/server/AlarmManagerService.java#L78-L82) recursion will not work either in this case.

New solution proposal: Start the service every 5 seconds and use a loop inside the service to monitor shorter intervals (like it was `long long ago;`)

**Comment by zhijiazheng123** [comment]
@twinone could you please create a new branch for me? I have some new updates, but not convenient to merge from the fork project.

**Comment by twinone** [comment]
https://github.com/twinone/AppLocker/tree/fix-android5.1

**Comment by twinone** [comment]
Any updates @zhijiazheng123 ?

**Comment by twinone** [comment]
I'm working on it. Should be fixed in some days.

Solution: Use a sticky foreground service (like applockservice was) that creates itself each 5 seconds via an AlarmManager. That way if it get's killed it's recreated within 5 seconds.

The service uses a Handler internally to run it's logic internally each 300ms

**Comment by twinone** [comment]
Fixed in 2a9d1624d129138175d4939b08e50590edc66508

**Comment by solankiranvir** [comment]
Can you please inform me when this issue solved.
Thanks

**Comment by twinone** [comment]
Can you please tell me what phone you use. On my phones it works fine. Also, are you available for testing?

**Comment by solankiranvir** [comment]
ya i am available. i m using moto e with 5.1 os.

**Comment by twinone** [comment]
Please test [this APK](https://www.twinone.org/AppLocker-test.apk)

**Comment by twinone** [comment]
Tested on some 5.1 devices:
Samsung Galaxy S5,
Samsung Galaxy S6,
Oneplus One (Stock and CyanogenMod)

**Comment by solankiranvir** [comment]
Ya sure i will test & tell you.
Thanks :-)

**Comment by solankiranvir** [comment]
Hey This apk also not work in Moto E with 5.1.
It also crash when cancel button press when set password.
It also not show password dot when enter password.
Thanks

**Comment by twinone** [comment]
Those two (#41 and #42) are now fixed.

Just to check, make sure when you open the app, you create a new password, and lock an app. Make sure in the left Navigation the app says "Locker is running", and then open the app.

In [this new APK](https://www.twinone.org/AppLocker-test2.apk) I've also added a toast whenever the app changes, so when you open ANY app, it's package name should show up on the screen. Can you check if that works?
