### ISSUE TITLE
Custom background won't be applied

### ISSUE THREAD

**Issue by tom-heimbrodt** [twinone/AppLocker#18]
It seems like selecting a custom background in settings has no effect. As far as I can see, it is stored but never applied. It doesn't matter if a color or an image from the gallery is chosen.
I've installed version 2.6.0 from F-Droid.

**Comment by zhijiazheng123** [comment]
I don't think this is an issue, 2.6.0 is designed to not support this.

**Comment by twinone** [comment]
No, it should work. I'll look into it when I have some time. I'm planning some big changes in the app.

**Comment by zhijiazheng123** [comment]
just change the bool variable pro to true can make it work, at file LockPreferences.java on line 23.

**Comment by twinone** [comment]
Oh, I thought I removed the pro features and made everything available to everyone.

**Comment by twinone** [comment]
Can you confirm it's fixed in d022b2c07820d000cbd221acbf8a7d5b4c1a68a6?

**Comment by tom-heimbrodt** [comment]
Yes it's fixed now.
Thank you!
