### ISSUE TITLE
The app turns off after a few seconds

### ISSUE THREAD

**Issue by bisemanu** [twinone/AppLocker#20]
On some smartphone there is the same problem, the app turns off after a few seconds, and no longer blocks the selected applications

http://www.youtube.com/watch?v=k9SPqh2Gnsc

**Comment by twinone** [comment]
Hi @bisemanu, sorry for the late reply. Do you use Android 5.1?

**Comment by twinone** [comment]
Possibly fixed in 2a9d1624d129138175d4939b08e50590edc66508
Could you check it? [here](https://www.twinone.org/AppLocker.apk)'s the APK

**Comment by twinone** [comment]
Closed until a response is received.
