### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by twinone** [twinone/AppLocker#23]
Should update to material and fix some other stuff.

**Comment by zhijiazheng123** [comment]
agree with you, please let me do this.

**Comment by twinone** [comment]
@zhijiazheng123 Did you say you wanted this issue?

**Comment by virues2007** [comment]
i have brought this material ui library

http://codecanyon.net/item/material-design-ui-android-template-app/9858746

if you want me to send it to you just tell :)

**Comment by zhijiazheng123** [comment]
yes, I said that, but I doubted the ability of myself to accomplish this task, so I removed it :)
but if you have confidence in me, please tell me your detail plan of 'update to material and fix some other stuff', I'll try my best to make this done.

**Comment by zhijiazheng123** [comment]
@ virues2007 Yes, please send it to me, thanks. does this ui library compatible with Android4.4 and lower version?

**Comment by twinone** [comment]
Just use the support library (v22+), it includes support for material design, including dialogs now.

**Comment by twinone** [comment]
I'll be available to do it in 4 or 5 days again

**Comment by zhijiazheng123** [comment]
May I have the honor to do this? you could focus on the issue #15 , which I think is more important for this app.
would you like to replace left Drawer by the FloatingActionButton like below?
![screenshot_2015-07-26-14-27-08](https://cloud.githubusercontent.com/assets/4221889/8894418/d0f9b37e-33e8-11e5-91c5-25efc1b93f13.png)

**Comment by zhijiazheng123** [comment]
Or maybe you want to use NavigationView to update current navigation drawer?

**Comment by twinone** [comment]
Oh! I didn't know it existed. That would be awesome. Go ahead if you wish with the NavigationView.

**Comment by zhijiazheng123** [comment]
ready for review this feature

**Comment by twinone** [comment]
Fixed in 027860dd68a3473e1ad2bbf4ddd3d207f04dadf0
