### ISSUE TITLE
Change app icon

### ISSUE THREAD

**Issue by twinone** [twinone/AppLocker#31]
This one is so ugly... Anybody good at designing?

**Comment by virues2007** [comment]
@twinone what about this ??
![portfolio 1](https://cloud.githubusercontent.com/assets/2973369/9001685/dc00b2b6-375a-11e5-88b2-33ca429d0c38.png)

**Comment by virues2007** [comment]
@twinone  this one without black background
![artwork](https://cloud.githubusercontent.com/assets/2973369/9001697/070170ea-375b-11e5-8924-00925a8196e7.png)

**Comment by twinone** [comment]
I was thinking about a bit more simplistic design - A lock on a material color background, but this one looks pretty cool too.

I'll think about it, it's a bit too complex for the small icon it will be.

**Comment by virues2007** [comment]
@twinone  another one :)
![twinone_icon](https://cloud.githubusercontent.com/assets/2973369/9003744/f0ff7b8c-3770-11e5-8da0-ec4635512708.png)

**Comment by twinone** [comment]
I appreciate it, but I don't want to copy an icon from somebody else.

**Comment by virues2007** [comment]
@twinone nobody uses this icon before ,,, also this icon is a royalty free

check this : 

http://www.flaticon.com/free-icon/padlock-lock-shape_34336

**Comment by twinone** [comment]
Fixed in 2a9d1624d129138175d4939b08e50590edc66508
