### ISSUE TITLE
Background loading

### ISSUE THREAD

**Issue by twinone** [twinone/AppLocker#36]
Optimize image loading.

Currently when the user selects a image from the Gallery to be the background image it's typically pretty big (multiple times bigger than the screen size). This slows down loading. And we're currently rotating the loaded image according to its EXIF tags, which dramatically slows down the process to show the lock screen when an app has been opened.

See the loading time difference with background enabled and disabled.

**Solution**:
* Loading a 4x smaller image into the background before showing the lock screen and loading the high-res image asynchronously. The user will se a pretty clear image get just a bit better after the big image got decoded.
* Rotate the image when the user picks it, instead of at loading time. This way we reduce the loading time significantly.

**Comment by tealhill** [comment]
May I suggest a simpler solution.

When the user selects a background image, rotate it, downscale it, and save a copy (with low JPEG quality) into internal storage.

Then, when you show the lock screen, load the pre-rotated and pre-downscaled image, and show it to the user.  How much time could this loading possibly take, even on an old and slow tablet with a high-resolution screen?

**Comment by tealhill** [comment]
Your idea is similar to "progressive JPEG decoding".  But progressive JPEG decoding is no longer popular anymore nowadays.  I don't know whether or not the image decoding libraries found preinstalled on an ordinary Android device will support progressive decoding.
