### ISSUE TITLE
ads issue 

### ISSUE THREAD

**Issue by virues2007** [twinone/AppLocker#4]
hi 
i have found an issue in ads ..  when i click on it nothing opened and i found this error on logcat

01-06 20:52:49.756: E/Ads(25609): JS: Uncaught ReferenceError: AFMA_ReceiveMessage is not defined (null:1)
01-06 20:52:49.756: E/Web Console(25609): Uncaught ReferenceError: AFMA_ReceiveMessage is not defined:1

here's also the solution for this issue 
http://stackoverflow.com/questions/21119062/afma-receivemessage-is-not-defined

**Comment by twinone** [comment]
Hello,
Do you mean the fullscreen ad or the banner?

I'll take a look at it, thanks!

**Comment by twinone** [comment]
I think the last commit 419b68ed6da5607ffc9943a5a2d7239849ff7379 fixed it. It works good for me at least. Could you confirm it's fixed?

**Comment by virues2007** [comment]
no still doesnt work i even download your app from playstore but still interstitial ad buggy

after i unlock 10 apps an interstitial ad will be viewed but its un-clickable

**Comment by twinone** [comment]
Yes, indeed, the intersitital is only showed every 10 locks, because I don't want to bother the user with too much advertisements. 1/10 is enough.

The test ad works for me, I can click it and it takes me to the page.
What phone and android version do you use?

**Comment by virues2007** [comment]
Phone :Samsung , version 4.2.2
Tablet version 4.4.2

**Comment by twinone** [comment]
Well, I've implemented the solution you provided at commit 5c538ad610be3d3ce13e3d67063e71c9a00e5282
[here](https://www.twinone.org/locker-fix-ads.apk) is the compiled apk if you want to test it.

**Comment by twinone** [comment]
(It's signed with my debug key)

**Comment by virues2007** [comment]
i got unfortunately , AppLocker has Stopper after unlocking 10 apps

**Comment by twinone** [comment]
I think I fixed it in commit 72a8eb50abaa87e7950897fa2c79f64474a5912c
[Compiled apk](https://www.twinone.org/locker-fix-ads2.apk) (Ads every 1 unlock instead of 10)

**Comment by virues2007** [comment]
Works Perfect!! ..... But its showed after closing the app

**Comment by twinone** [comment]
Indeed it shows after the locked app closes.

The monetization of the app will not be changed.

I'll close this issue now since you said it works perfectly.
