### ISSUE TITLE
Type mismatch: cannot convert from SettingsFragment to Fragment

### ISSUE THREAD

**Issue by erumhannan** [twinone/AppLocker#5]
inside this package org/twinone/locker/ui  ---------------->MainActivity.java file line 301 switch (type) {
		case NavigationElement.TYPE_APPS:
			mCurrentFragment = new AppsFragment();
			break;
		case NavigationElement.TYPE_SETTINGS:
			mCurrentFragment = new SettingsFragment();
			break;

mCurrentFragment = new SettingsFragment();  getting error here Type mismatch: cannot convert from SettingsFragment to Fragment

**Comment by erumhannan** [comment]
can u pls tell me about eclipse i m not using android studio

**Comment by twinone** [comment]
I'm not supporting eclipse builds anymore, sorry.
I didn't fully understand the other question but maybe [this](https://github.com/twinone/AppLocker/blob/634dc220d45d126b07bbed33445b39885d760d5a/app/src/main/java/org/twinone/locker/ui/AppsFragment.java#L54-67) and [this](https://github.com/twinone/AppLocker/blob/634dc220d45d126b07bbed33445b39885d760d5a/app/src/main/java/org/twinone/locker/appselect/AppAdapter.java#L314-L326) is what you're looking for.
