### ISSUE TITLE
LICENSE & Releases

### ISSUE THREAD

**Issue by Zillode** [twinone/AppLocker#7]
Hi, I wrote metadata for the AppLocker app to get it accepted in the [F-Droid](https://f-droid.org) store. F-Droid builds all apps from source such that users can install untampered open-source applications.

To finish the F-Droid store inclusion process, I just need you to add a license to your repo (GPLv3, MIT, MPLv2, ...) and create a [release](https://github.com/twinone/AppLocker/releases). Afterwards, every new release will automatically trigger a recompilation by the F-Droid platform such that users can update their app.

A bitcoin address can also be added to your app metadata, feel free to post it here. Thanks

**Comment by twinone** [comment]
Done. Nice to have it in F-Droid, I haven't thought about that yet. Please let me know if there's anything else I have to do.

**Comment by Zillode** [comment]
Thanks, should be good to go but it can take a couple of days before it is available in the store.

**Comment by ashu9415** [comment]
in this project we face the error dsl method not found possible cause plugin and wrapper file how can i resolve it plzz reply
